### ISSUE TITLE
What are the minimal system requirements?

### ISSUE THREAD

**Issue by pizza-777** [broxus/everscale-monitoring#2]

**Comment by Rexagon** [comment]
It is a small node so possible requirements are like this:

CPU: 4 cores, 2 GHz
RAM: 8 GB
Storage: 100 GB fast SSD
Network: 100 MBit/s

Btw, today was an update with sync fix so if you are trying to run it using the commit before 096408950 it will stuck. In that case just rebuild it from master and restart the service
